spec-version: 0.36.0
name: skm
version: 0.1.0
synopsis: Tool for the SKM language
author: Alexandra Zaldivar Aiello
github: lexzaiello/sk-lean
category: Language

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base >= 4.14 && < 5
  - optparse-applicative == 0.18.1.0
  - megaparsec == 9.7.0
  - text >= 2.0.0
  - transformers >= 0.6.0.0
  - containers >= 0.6.7

library:
  source-dirs: src
  exposed-modules:
    - Skm.Ast
    - Skm.Eval
    - Skm.Vm
    - Skm.Parse
    - Skm.Std
    - Skm.Compiler.Ast
    - Skm.Compiler.Parse
    - Skm.Compiler.ProofGen
    - Skm.Compiler.Translate
  other-modules:
    - Skm.Util.Parsing

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - skm
