spec-version: 0.36.0
name: skm
version: 0.1.0
synopsis: Tool for the SKM language
author: Alexandra Zaldivar Aiello
github: lexzaiello/sk-lean
category: Language

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base
  - optparse-applicative
  - megaparsec
  - text
  - transformers
  - containers
  - hashable
  - unordered-containers
  - mtl
  - hspec
  - array == 0.5.8.0
  - haskeline

library:
  source-dirs: src
  exposed-modules:
    - Skm
    - Skm.Ast
    - Skm.Eval
    - Skm.Vm
    - Skm.Parse
    - Skm.Typecheck
    - Skm.Compiler.Ast
    - Skm.Compiler.Parse
    - Skm.Compiler.ProofGen
    - Skm.Compiler.Translate
    - Skm.Util.Parsing
    - Skm.Cli.OptParse
    - Skm.Cli.Exec
    - Skm.Cli.Repl

tests:
  spec:
    main:        Main.hs
    source-dirs: test
    dependencies:
      - skm

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - skm
