name = "sk-lean"
version = "0.1.0"
defaultTargets = ["SkLean"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.22.0-rc4"

[[lean_lib]]
name = "SkLean"
